import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

export const metadata = {
  title: "Bg-Removel",
  description: "Generated by David Pal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  antialiased `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
