import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Bg-Removel",
  description: "Generated by David Pal",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`  antialiased `}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
